import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '../../styles/Profile.module.scss';

const Home: NextPage = () => {
  const router = useRouter();
  const { name } = router.query;

  return (
    <div>
      <Head>
        <title>{name}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main id='main'>
        <div id='card'></div>

        <button id='createAccBtn'></button>
      </main>
    </div>
  );
};

export default Home;
